[book]
title = "mdbook-template"
authors = ["hyeondg"]
description = "A template for MDBook"

[output.html]
theme = "src/theme"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true 
no-section-label = false
additional-css = ["src/custom.css"]

[output.html.fold]
enable = false
level = 0

[output.html.print]
enable = true
